<a href="https://colab.research.google.com/github/likhon15-4915/OOPII_Python/blob/main/OOP10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
#1D
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [ ]:
#2D
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
#3D
c=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,16]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 16]])

In [ ]:
#datatype
d=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,16]],dtype=np.float128)
d

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 16.]], dtype=float128)

In [ ]:
d.size

15

In [ ]:
d.shape

(3, 5)

In [ ]:
d.dtype

dtype('float128')

In [ ]:
d.itemsize

16

**Array Functions in numpy**

In [ ]:
d.max()

16.0

In [ ]:
d.min()

1.0

In [ ]:
d.sum()

121.0

In [ ]:
d.mean()

8.066666666666666667

In [ ]:
d.std()

4.434210439550904109

In [ ]:
d.var()

19.66222222222222222

In [ ]:
np.sqrt(d)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766],
       [3.31662479, 3.46410162, 3.60555128, 3.74165739, 4.        ]],
      dtype=float128)

**Array** **Sum**

In [ ]:
x=np.array([1,2,3,4,5])
y=np.array([6,7,8,9,10])
x+y

array([ 7,  9, 11, 13, 15])

In [ ]:
x=np.array([1,2,3,4,5])
x<5

array([ True,  True,  True,  True, False])

In [ ]:
only_one= np.ones([3,4])
only_one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
only_one= np.zeros([2,2,3,4])
only_one

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

**Random**

In [ ]:
ran= np.random.random((5,5))
ran

array([[0.76555675, 0.6709058 , 0.08279812, 0.50156802, 0.04809566],
       [0.56805997, 0.30502764, 0.14419147, 0.36607841, 0.76575995],
       [0.34387818, 0.70602874, 0.08694707, 0.28674195, 0.67509583],
       [0.71953617, 0.44086846, 0.78466307, 0.62252917, 0.0067108 ],
       [0.04092968, 0.32885286, 0.24561514, 0.07999266, 0.18433359]])

In [ ]:
ran2= np.random.randint(100,size=(5,5))
ran2

array([[27, 56, 73, 10,  0],
       [ 6, 80, 82, 73, 55],
       [86, 60, 96, 47,  7],
       [61, 75, 67, 22, 87],
       [49, 55, 78, 64, 37]])

In [ ]:
ran3= np.random.randint(-15,-1,size=(5,5))
ran3

array([[ -4,  -2, -10,  -4,  -3],
       [-13,  -8, -11,  -8,  -8],
       [ -7,  -6,  -3,  -2,  -4],
       [ -6, -15,  -4, -10, -10],
       [ -7, -12,  -6,  -4,  -2]])

**Array** **Reshape**

In [ ]:
p=np.array([[1,2,3],[4,5,6]])
q=p.reshape(3,2)
print(q)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
q=p.reshape(2,3)
q

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
q=p.reshape(3,2)

**Array Slicing using numpy**

In [ ]:
p=np.array([[1,2,3],[4,5,6]])
